version: '3.8'

services:
  back-end:
    container_name: back-end
    restart: always
    ports:
      - 8000:8000
    build:
      context: ./server/
      dockerfile: Dockerfile
  front-end:
    container_name: front-end
    restart: always
    ports:
      - 80:80
    build:
      context: ./client/
      dockerfile: Dockerfile
